# Generated by Django 5.0.2 on 2024-03-05 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friends",
            name="friend",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friend",
                to="chat.userprofile",
            ),
        ),
        migrations.DeleteModel(
            name="Messages",
        ),
    ]
