# Generated by Django 5.0.2 on 2024-06-24 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_friends_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friends',
            options={'verbose_name_plural': 'Friends'},
        ),
        migrations.AlterModelOptions(
            name='keys',
            options={'verbose_name_plural': 'Keys'},
        ),
    ]
