# Generated by Django 5.0.2 on 2024-06-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_friends_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friends',
            options={'ordering': ['user', 'friend'], 'verbose_name': 'Friend', 'verbose_name_plural': 'Friends'},
        ),
        migrations.AlterModelOptions(
            name='keys',
            options={'ordering': ['user'], 'verbose_name': 'Key', 'verbose_name_plural': 'Keys'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['name'], 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterField(
            model_name='friends',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
