# Generated by Django 5.0.2 on 2024-03-24 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facts',
            options={'verbose_name_plural': 'Facts'},
        ),
    ]
