# Generated by Django 5.0.2 on 2024-06-24 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_facts_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_type',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
